# Generated by Django 4.2.1 on 2023-05-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart_charity', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(upload_to='')),
                ('detail', models.CharField(max_length=500)),
                ('raised', models.FloatField()),
                ('goal', models.FloatField()),
            ],
        ),
    ]
